import type { ThemeStyleValues } from "@/lib/validations/bio";

export type ThemePreset = {
  id: string;
  name: string;
  description: string;
  style: Pick<
    ThemeStyleValues,
    | "themeName"
    | "primaryColor"
    | "secondaryColor"
    | "accentColor"
    | "textColor"
    | "backgroundColor"
    | "buttonBackground"
    | "buttonText"
    | "backgroundType"
    | "gradientFrom"
    | "gradientTo"
    | "fontFamily"
    | "fontSize"
    | "fontWeight"
    | "buttonStyle"
    | "buttonRadius"
    | "cardStyle"
    | "blockSpacing"
    | "alignment"
  >;
};

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "typeform",
    name: "Typeform",
    description: "Eggplant ink on warm off-white with Tobias serif accent.",
    style: {
      themeName: "light",
      primaryColor: "#2a222b",
      secondaryColor: "#564b58",
      accentColor: "#a25fba",
      textColor: "#2a222b",
      backgroundColor: "#faf9fb",
      buttonBackground: "#2a222b",
      buttonText: "#faf9fb",
      backgroundType: "solid",
      gradientFrom: "#faf9fb",
      gradientTo: "#faf9fb",
      fontFamily: "Source Serif 4, Georgia, serif",
      fontSize: "16px",
      fontWeight: "400",
      buttonStyle: "solid",
      buttonRadius: "12px",
      cardStyle: "shadow",
      blockSpacing: "16px",
      alignment: "center",
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Clean, light and airy with a subtle indigo accent.",
    style: {
      themeName: "light",
      primaryColor: "#6366f1",
      secondaryColor: "#a855f7",
      accentColor: "#22d3ee",
      textColor: "#18181b",
      backgroundColor: "#ffffff",
      buttonBackground: "#18181b",
      buttonText: "#ffffff",
      backgroundType: "solid",
      gradientFrom: "#ffffff",
      gradientTo: "#ffffff",
      fontFamily: "Inter, sans-serif",
      fontSize: "16px",
      fontWeight: "500",
      buttonStyle: "solid",
      buttonRadius: "12px",
      cardStyle: "shadow",
      blockSpacing: "12px",
      alignment: "center",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Deep charcoal with soft indigo and violet highlights.",
    style: {
      themeName: "dark",
      primaryColor: "#818cf8",
      secondaryColor: "#c084fc",
      accentColor: "#22d3ee",
      textColor: "#f4f4f5",
      backgroundColor: "#09090b",
      buttonBackground: "#27272a",
      buttonText: "#fafafa",
      backgroundType: "solid",
      gradientFrom: "#09090b",
      gradientTo: "#09090b",
      fontFamily: "Inter, sans-serif",
      fontSize: "16px",
      fontWeight: "500",
      buttonStyle: "solid",
      buttonRadius: "12px",
      cardStyle: "shadow",
      blockSpacing: "12px",
      alignment: "center",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm ember-to-night gradient with pill-shaped buttons.",
    style: {
      themeName: "dark",
      primaryColor: "#fb923c",
      secondaryColor: "#f43f5e",
      accentColor: "#fbbf24",
      textColor: "#fff7ed",
      backgroundColor: "#0c0a09",
      buttonBackground: "#f97316",
      buttonText: "#ffffff",
      backgroundType: "gradient",
      gradientFrom: "#7c2d12",
      gradientTo: "#0c0a09",
      fontFamily: "Inter, sans-serif",
      fontSize: "16px",
      fontWeight: "600",
      buttonStyle: "solid",
      buttonRadius: "9999px",
      cardStyle: "shadow",
      blockSpacing: "14px",
      alignment: "center",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Cool aqua and sky tones over a breezy gradient.",
    style: {
      themeName: "light",
      primaryColor: "#0ea5e9",
      secondaryColor: "#06b6d4",
      accentColor: "#3b82f6",
      textColor: "#0f172a",
      backgroundColor: "#f0f9ff",
      buttonBackground: "#0ea5e9",
      buttonText: "#ffffff",
      backgroundType: "gradient",
      gradientFrom: "#e0f2fe",
      gradientTo: "#f0f9ff",
      fontFamily: "Inter, sans-serif",
      fontSize: "16px",
      fontWeight: "500",
      buttonStyle: "solid",
      buttonRadius: "12px",
      cardStyle: "shadow",
      blockSpacing: "12px",
      alignment: "center",
    },
  },
  {
    id: "forest",
    name: "Forest",
    description: "Rich pine greens with a fresh emerald pop.",
    style: {
      themeName: "dark",
      primaryColor: "#22c55e",
      secondaryColor: "#10b981",
      accentColor: "#84cc16",
      textColor: "#ecfdf5",
      backgroundColor: "#052e16",
      buttonBackground: "#16a34a",
      buttonText: "#ffffff",
      backgroundType: "solid",
      gradientFrom: "#052e16",
      gradientTo: "#052e16",
      fontFamily: "Inter, sans-serif",
      fontSize: "16px",
      fontWeight: "500",
      buttonStyle: "solid",
      buttonRadius: "12px",
      cardStyle: "shadow",
      blockSpacing: "12px",
      alignment: "center",
    },
  },
  {
    id: "rose",
    name: "Rose",
    description: "Soft blush pink with playful pill-shaped buttons.",
    style: {
      themeName: "light",
      primaryColor: "#e11d48",
      secondaryColor: "#f43f5e",
      accentColor: "#fb7185",
      textColor: "#1c1917",
      backgroundColor: "#fff1f2",
      buttonBackground: "#e11d48",
      buttonText: "#ffffff",
      backgroundType: "gradient",
      gradientFrom: "#ffe4e6",
      gradientTo: "#fff1f2",
      fontFamily: "Inter, sans-serif",
      fontSize: "16px",
      fontWeight: "600",
      buttonStyle: "solid",
      buttonRadius: "9999px",
      cardStyle: "shadow",
      blockSpacing: "12px",
      alignment: "center",
    },
  },
  {
    id: "neon",
    name: "Neon",
    description: "Electric cyan and magenta glow on deep space black.",
    style: {
      themeName: "dark",
      primaryColor: "#22d3ee",
      secondaryColor: "#e879f9",
      accentColor: "#a3e635",
      textColor: "#e2e8f0",
      backgroundColor: "#020617",
      buttonBackground: "#22d3ee",
      buttonText: "#020617",
      backgroundType: "gradient",
      gradientFrom: "#0f172a",
      gradientTo: "#020617",
      fontFamily: "Space Grotesk, Inter, sans-serif",
      fontSize: "16px",
      fontWeight: "600",
      buttonStyle: "outline",
      buttonRadius: "10px",
      cardStyle: "flat",
      blockSpacing: "12px",
      alignment: "center",
    },
  },
  {
    id: "cream",
    name: "Cream",
    description: "Warm paper tones, serif type and soft shadows.",
    style: {
      themeName: "light",
      primaryColor: "#b45309",
      secondaryColor: "#ea580c",
      accentColor: "#a16207",
      textColor: "#292524",
      backgroundColor: "#fdf6ec",
      buttonBackground: "#1c1917",
      buttonText: "#fafaf9",
      backgroundType: "solid",
      gradientFrom: "#fdf6ec",
      gradientTo: "#fdf6ec",
      fontFamily: "Lora, Georgia, serif",
      fontSize: "17px",
      fontWeight: "500",
      buttonStyle: "solid",
      buttonRadius: "8px",
      cardStyle: "shadow",
      blockSpacing: "14px",
      alignment: "center",
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    description: "Bold black-on-white with sharp corners and serif type.",
    style: {
      themeName: "light",
      primaryColor: "#000000",
      secondaryColor: "#525252",
      accentColor: "#a3a3a3",
      textColor: "#171717",
      backgroundColor: "#fafafa",
      buttonBackground: "#171717",
      buttonText: "#fafafa",
      backgroundType: "solid",
      gradientFrom: "#fafafa",
      gradientTo: "#fafafa",
      fontFamily: "Playfair Display, Georgia, serif",
      fontSize: "16px",
      fontWeight: "500",
      buttonStyle: "solid",
      buttonRadius: "0px",
      cardStyle: "outlined",
      blockSpacing: "12px",
      alignment: "left",
    },
  },
  {
    id: "aurora",
    name: "Aurora",
    description: "Twilight violet gradient with dreamy pill buttons.",
    style: {
      themeName: "dark",
      primaryColor: "#a78bfa",
      secondaryColor: "#f472b6",
      accentColor: "#67e8f9",
      textColor: "#f5f3ff",
      backgroundColor: "#1e1b4b",
      buttonBackground: "#8b5cf6",
      buttonText: "#ffffff",
      backgroundType: "gradient",
      gradientFrom: "#4c1d95",
      gradientTo: "#1e1b4b",
      fontFamily: "Inter, sans-serif",
      fontSize: "16px",
      fontWeight: "500",
      buttonStyle: "solid",
      buttonRadius: "9999px",
      cardStyle: "shadow",
      blockSpacing: "12px",
      alignment: "center",
    },
  },
];

export const DEFAULT_THEME: ThemeStyleValues = {
  themeName: "light",
  preset: "typeform",
  primaryColor: "#2a222b",
  secondaryColor: "#564b58",
  accentColor: "#a25fba",
  textColor: "#2a222b",
  backgroundColor: "#faf9fb",
  buttonBackground: "#2a222b",
  buttonText: "#faf9fb",
  fontFamily: "Source Serif 4, Georgia, serif",
  fontSize: "16px",
  fontWeight: "400",
  backgroundType: "solid",
  gradientFrom: "#faf9fb",
  gradientTo: "#faf9fb",
  backgroundImage: "",
  buttonStyle: "solid",
  buttonRadius: "12px",
  cardStyle: "shadow",
  blockSpacing: "16px",
  alignment: "center",
  customCss: "",
};

export function getPreset(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find((p) => p.id === id);
}

export function applyPresetToTheme(theme: ThemeStyleValues, presetId: string): ThemeStyleValues {
  const preset = getPreset(presetId);
  if (!preset) return theme;
  return { ...theme, ...preset.style, preset: presetId };
}

export function mergeTheme(base: ThemeStyleValues, partial: Partial<ThemeStyleValues>): ThemeStyleValues {
  return { ...DEFAULT_THEME, ...base, ...partial };
}